import os
from shared.tracing import trace
from tools import (
    generate_patch,
    clone_repo,
    create_branch,
    apply_patch,
    run_tests_sandbox,
    commit_and_push,
    create_pr,
)


@trace("remediation_agent")
async def run_remediation(incident_id: str, rca_result: dict) -> dict:
    root_cause = rca_result.get("root_cause", "Unknown root cause")
    suspect_file = rca_result.get("suspect_file") or "demo/target_app/app.py"
    suspect_lines = rca_result.get("suspect_lines") or ""
    confidence = rca_result.get("confidence", 0.0)

    repo_dir = await clone_repo(incident_id)
    branch = await create_branch(repo_dir, incident_id)

    patch = None
    for attempt in range(3):
        source_code = ""
        suspect_path = os.path.join(repo_dir, suspect_file)
        if os.path.exists(suspect_path):
            with open(suspect_path) as f:
                source_code = f.read()

        patch = await generate_patch(root_cause, suspect_file, suspect_lines, source_code)
        patch_content = patch.get("patch", "")

        if not patch_content:
            continue

        applied = await apply_patch(repo_dir, patch_content)
        if not applied:
            continue

        test_result = await run_tests_sandbox(repo_dir)
        if test_result.get("success"):
            break
        else:
            print(f"[remediation] Tests failed (attempt {attempt + 1}/3): {test_result.get('stderr', '')[:200]}")

    change_lines = patch.get("change_lines", 0) if patch else 0
    auto_merge = change_lines < 20

    title = f"fix: {root_cause[:100]}"
    body = f"""## Automated Fix by Sentinel

**Incident:** {incident_id}
**Root Cause:** {root_cause}
**Confidence:** {confidence}

### Changes
{patch.get('explanation', '') if patch else 'No patch generated'}

### Patch
```
{patch.get('patch', '')[:2000] if patch else 'N/A'}
```

---
_Generated by Sentinel Autonomous Incident Commander_
"""

    if patch and patch.get("patch"):
        msg = patch.get("explanation", f"Fix for {root_cause[:60]}")
        commit_msg = f"sentinel: fix incident {incident_id[:8]} - {msg}"
        await commit_and_push(repo_dir, incident_id, commit_msg)

        pr_result = await create_pr(
            incident_id, branch, title, body, auto_merge=auto_merge
        )
    else:
        pr_result = {"error": "No patch could be generated after 3 attempts"}

    return {
        "incident_id": incident_id,
        "root_cause": root_cause,
        "patch": patch.get("patch", "") if patch else "",
        "change_lines": change_lines,
        "auto_merge": auto_merge,
        "pr": pr_result,
        "branch": branch,
    }


